# Generated by Django 4.2 on 2023-08-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
