# Generated by Django 4.2 on 2023-08-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_user_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='myUser',
        ),
    ]
