# Generated by Django 4.2 on 2023-08-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_myuser_image_name_post_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='multipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(max_length=250, null=True, upload_to='multiple_image/')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.FileField(max_length=200, null=True, upload_to='image/'),
        ),
    ]
